/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as PaginaSlugRouteImport } from './routes/pagina.$slug'
import { Route as MinhaContaPedidosRouteImport } from './routes/minha-conta.pedidos'
import { Route as MinhaContaPagamentosRouteImport } from './routes/minha-conta.pagamentos'
import { Route as MinhaContaEnderecosRouteImport } from './routes/minha-conta.enderecos'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPaginasRouteImport } from './routes/admin.paginas'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'
import { Route as AdminLogisticaRouteImport } from './routes/admin.logistica'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminDistribuidorasRouteImport } from './routes/admin.distribuidoras'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCombosRouteImport } from './routes/admin.combos'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosEditarIdRouteImport } from './routes/admin.produtos.editar.$id'

const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginaSlugRoute = PaginaSlugRouteImport.update({
  id: '/pagina/$slug',
  path: '/pagina/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaPedidosRoute = MinhaContaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaPagamentosRoute = MinhaContaPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaEnderecosRoute = MinhaContaEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => MinhaContaRoute,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasRoute = AdminPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistribuidorasRoute = AdminDistribuidorasRouteImport.update({
  id: '/distribuidoras',
  path: '/distribuidoras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCombosRoute = AdminCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosEditarIdRoute = AdminProdutosEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/combos': typeof AdminCombosRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/distribuidoras': typeof AdminDistribuidorasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/pagamentos': typeof MinhaContaPagamentosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/editar/$id': typeof AdminProdutosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/combos': typeof AdminCombosRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/distribuidoras': typeof AdminDistribuidorasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/pagamentos': typeof MinhaContaPagamentosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/editar/$id': typeof AdminProdutosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/entrar': typeof EntrarRoute
  '/favoritos': typeof FavoritosRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/combos': typeof AdminCombosRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/distribuidoras': typeof AdminDistribuidorasRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/minha-conta/enderecos': typeof MinhaContaEnderecosRoute
  '/minha-conta/pagamentos': typeof MinhaContaPagamentosRoute
  '/minha-conta/pedidos': typeof MinhaContaPedidosRoute
  '/pagina/$slug': typeof PaginaSlugRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/editar/$id': typeof AdminProdutosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/entrar'
    | '/favoritos'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/combos'
    | '/admin/cupons'
    | '/admin/distribuidoras'
    | '/admin/estoque'
    | '/admin/logistica'
    | '/admin/loja'
    | '/admin/marcas'
    | '/admin/paginas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/categoria/$slug'
    | '/minha-conta/enderecos'
    | '/minha-conta/pagamentos'
    | '/minha-conta/pedidos'
    | '/pagina/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/novo'
    | '/admin/produtos/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/entrar'
    | '/favoritos'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/combos'
    | '/admin/cupons'
    | '/admin/distribuidoras'
    | '/admin/estoque'
    | '/admin/logistica'
    | '/admin/loja'
    | '/admin/marcas'
    | '/admin/paginas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/categoria/$slug'
    | '/minha-conta/enderecos'
    | '/minha-conta/pagamentos'
    | '/minha-conta/pedidos'
    | '/pagina/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/novo'
    | '/admin/produtos/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/entrar'
    | '/favoritos'
    | '/minha-conta'
    | '/pedido-confirmado'
    | '/admin/avaliacoes'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/combos'
    | '/admin/cupons'
    | '/admin/distribuidoras'
    | '/admin/estoque'
    | '/admin/logistica'
    | '/admin/loja'
    | '/admin/marcas'
    | '/admin/paginas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/categoria/$slug'
    | '/minha-conta/enderecos'
    | '/minha-conta/pagamentos'
    | '/minha-conta/pedidos'
    | '/pagina/$slug'
    | '/pedido/$id'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/novo'
    | '/admin/produtos/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  EntrarRoute: typeof EntrarRoute
  FavoritosRoute: typeof FavoritosRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  PaginaSlugRoute: typeof PaginaSlugRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagina/$slug': {
      id: '/pagina/$slug'
      path: '/pagina/$slug'
      fullPath: '/pagina/$slug'
      preLoaderRoute: typeof PaginaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/pedidos': {
      id: '/minha-conta/pedidos'
      path: '/pedidos'
      fullPath: '/minha-conta/pedidos'
      preLoaderRoute: typeof MinhaContaPedidosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/pagamentos': {
      id: '/minha-conta/pagamentos'
      path: '/pagamentos'
      fullPath: '/minha-conta/pagamentos'
      preLoaderRoute: typeof MinhaContaPagamentosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/enderecos': {
      id: '/minha-conta/enderecos'
      path: '/enderecos'
      fullPath: '/minha-conta/enderecos'
      preLoaderRoute: typeof MinhaContaEnderecosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas': {
      id: '/admin/paginas'
      path: '/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AdminPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/distribuidoras': {
      id: '/admin/distribuidoras'
      path: '/distribuidoras'
      fullPath: '/admin/distribuidoras'
      preLoaderRoute: typeof AdminDistribuidorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/combos': {
      id: '/admin/combos'
      path: '/combos'
      fullPath: '/admin/combos'
      preLoaderRoute: typeof AdminCombosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/editar/$id': {
      id: '/admin/produtos/editar/$id'
      path: '/editar/$id'
      fullPath: '/admin/produtos/editar/$id'
      preLoaderRoute: typeof AdminProdutosEditarIdRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosEditarIdRoute: typeof AdminProdutosEditarIdRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosEditarIdRoute: AdminProdutosEditarIdRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminCombosRoute: typeof AdminCombosRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminDistribuidorasRoute: typeof AdminDistribuidorasRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminLojaRoute: typeof AdminLojaRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminPaginasRoute: typeof AdminPaginasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminCombosRoute: AdminCombosRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminDistribuidorasRoute: AdminDistribuidorasRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminLojaRoute: AdminLojaRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminPaginasRoute: AdminPaginasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaEnderecosRoute: typeof MinhaContaEnderecosRoute
  MinhaContaPagamentosRoute: typeof MinhaContaPagamentosRoute
  MinhaContaPedidosRoute: typeof MinhaContaPedidosRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaEnderecosRoute: MinhaContaEnderecosRoute,
  MinhaContaPagamentosRoute: MinhaContaPagamentosRoute,
  MinhaContaPedidosRoute: MinhaContaPedidosRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BuscarRoute: BuscarRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  EntrarRoute: EntrarRoute,
  FavoritosRoute: FavoritosRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  PaginaSlugRoute: PaginaSlugRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
